### PR TITLE
reason to denial reason

### PR DESCRIPTION
**Pull request by ArushC**
### [Pivotal Tracker Link][tracker]

[tracker]: https://www.pivotaltracker.com/story/show/187044290

## What this PR does:

Replace the "reason" parameter with "denial_reason". Also updates the name of all relevant instance variables and attributes from "reason" to "denial_reason" to avoid confusion in the code, except in the one case where the @ reason instance variable was being used both for the denial reason and the more information request reason (not implemented yet)—here, I added a new instance variable @reason_request for the more information request in the relevant controller to pass along the information.

IMPORTANT: to reflect the changes in the denial email template (changing {reason} to {denial reason}), the EmailTemplate database needs to be either reseeded or edited manually through the web interface by an admin: just change {reason | ...} to {denial_reason | ...} in the email template. Also, the request more info email template should be changed to use {request_reason | ...} instead of {reason | ...}.

This pull request fixes|implements (pick one...) ______.

#### Who authored this PR?

@ArushC 

### How should this PR be tested?

* Is there a deploy we can view?
* What do the specs/features test?
* Are there edge cases to watch out for?

### Checklist:

- [x] Has this been deployed to a staging environment or reviewed by a customer?
- [x] Tag someone for code review (either a coach / team member)
- [x] I have renamed the branch to match PivotTracker's suggested one (necessary for BlueJay) (e.g. `michael/12345-add-new-feature` Any branch name will do as long as the story ID is there. You can use `git checkout -b [new-branch-name]`)

### CODE REVIEW

**Comment by fp456** [comment]
LGTM. Branch name seems correct, as well the overall quality of the PR.

**Comment by perryzjc** [comment]
Is this {reason} field still supposed to exist here?
image

I can notice the {reason} at the `Allowed Tags` is changed to {{denial_reason}}, which is expected:
image

**Comment by perryzjc** [comment]
For other renaming issues, I think it's fine. We can fix it when implementing `request_reason` feature.

**Comment by ArushC** [comment]
@perryzjc the reason field is not supposed to exist where you pointed out. But this can be updated manually through the user interface. It is probably much easier than generating a custom migration to update only that single field. I mentioned in the PR description:

"IMPORTANT: to reflect the changes in the denial email template (changing {reason} to {denial reason}), the EmailTemplate database needs to be either reseeded or edited manually through the web interface by an admin: just change {reason | ...} to {denial_reason | ...} in the email template. Also, the request more info email template should be changed to use {request_reason | ...} instead of {reason | ...}."

**Pull request merged**
